[versions]
openbis = "20.10.6"
openbis-common = "r20230123"
kotlinx-serialization = "1.4.1"
kotlinx-cli = "0.3.5"
kotlin = "1.7.20"
modelmapper = "3.0.0"
cisd-hotdeploy="13.01.0"
poi="5.2.3"
openbis-client=""
[libraries]
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
openbis = { module = "openbis:openbis-v3-api", version.ref = "openbis" }
openbis-common = { module = "openbis:common", version.ref = "openbis-common" }
openbis-dss = {module="openbis:dss", version.ref="openbis-client"}
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
test = { module = "org.jetbrains.kotlin:test"}
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
kotlinx-cli = { module = "org.jetbrains.kotlinx:kotlinx-cli", version.ref = "kotlinx-cli" }
jakarta-mail = { module = "jakarta.mail:jakarta.mail-api", version = "latest.release" }
jackson-databind = {module = "com.fasterxml.jackson.core:jackson-databind", version = "latest.release"}
kotlin-stdlib = {module="org.jetbrains.kotlin:kotlin-stdlib-jdk8"}
kotlin-bom = {module="org.jetbrains.kotlin:kotlin-bom", version="latest.release"}
junit = {module="junit:junit", version="4.13"}
modelmapper = {module="org.modelmapper:modelmapper", version.ref="modelmapper"}
cisd-hotdeploy = {module="cisd:cisd-hotdeploy", version.ref="cisd-hotdeploy"}
poi = {module="org.apache.poi:poi", version.ref="poi"}
poi-ooxml = {module="org.apache.poi:poi-ooxml", version.ref="poi"}
[plugins]
kotlin = {id = "org.jetbrains.kotlin.jvm", version.ref="kotlin"}
kotlin-serialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref="kotlin"}
dockerCompose = { id = "com.avast.gradle.docker-compose", version = "0.16.11" }
fatJar = {id="io.ktor.plugin", version="2.2.3"}
download = {id="de.undercouch.download", version="5.4.0"}